const Constants = {
  ACTIVE_LAB_PDF: "ACTIVE_LAB_PDF",
  ACTIVE_DOC_PDF: "ACTIVE_DOC_PDF",
  AUTH_USER: "AUTH_USER",
  UNAUTH_USER: "UNAUTH_USER",
  AUTH_ERROR: "AUTH_ERROR",
  CLEAR_AUTH_ERROR: "CLEAR_AUTH_ERROR",
  LOGOUT_USER: "LOGOUT_USER",

  SET_USER_ID :"SET_USER_ID",

  REQUEST_USER_INFO : "REQUEST_USER_INFO",
  RECEIVE_USER_INFO : "RECEIVE_USER_INFO",
  RECEIVE_USER_INFO_ERROR : "RECEIVE_USER_INFO_ERROR",


  REQUEST_COURSES_LAB_INFO : "REQUEST_COURSES_LAB_INFO",
  RECEIVE_COURSES_LAB_INFO : "RECEIVE_COURSES_LAB_INFO",

  REQUEST_COURSES_VLAB_INFO : "REQUEST_COURSES_VLAB_INFO",
  RECEIVE_COURSES_VLAB_INFO : "RECEIVE_COURSES_VLAB_INFO",

  SET_COURSES_LAB : "SET_COURSES_LAB",
  SET_COURSES_VLAB : "SET_COURSES_VLAB",
  SET_VIRL_DATA : "SET_VIRL_INFO",

  IS_FETCHING_USER: "IS_FETCHING_USER",
  FETCH_USER_DATA: "FETCH_USER_DATA",

  REQUEST_SIMULATION: "REQUEST_SIMULATION",
  RECEIVE_SIMULATION: "RECEIVE_SIMULATION",


  REQUEST_ALL_SIMULATIONS: "REQUEST_ALL_SIMULATIONS",
  RECEIVE_ALL_SIMULATIONS: "RECEIVE_ALL_SIMULATIONS",

  REQUEST_SIMULATION_START: "REQUEST_SIMULATION_START",
  RECEIVE_SIMULATION_START: "RECEIVE_SIMULATION_START",

  REQUEST_SIMULATION_STOP: "REQUEST_SIMULATION_STOP",
  RECEIVE_SIMULATION_STOP: "RECEIVE_SIMULATION_STOP",

  REQUEST_SIMULATION_STOP_ALL: "REQUEST_SIMULATION_STOP_ALL",
  RECEIVE_SIMULATION_STOP_ALL: "RECEIVE_SIMULATION_STOP_ALL",

  REMOVE_SIMULATION: "REMOVE_SIMULATION",
  RESET_ALL_DATA: "RESET_ALL_DATA",

  REQUEST_SIMULATION_NODES: "REQUEST_SIMULATION_NODES",
  RECEIVE_SIMULATION_NODES: "RECEIVE_SIMULATION_NODES",

  REQUEST_SIMULATION_NODES_LINKS: "REQUEST_SIMULATION_NODES_LINKS",
  RECEIVE_SIMULATION_NODES_LINKS: "RECEIVE_SIMULATION_NODES_LINKS",


  RECEIVE_ERRORS: "RECEIVE_ERRORS",

  REQUEST_SIMULATION_LOGS: "REQUEST_SIMULATION_LOGS",
  RECEIVE_SIMULATION_LOGS: "RECEIVE_SIMULATION_LOGS",

  REQUEST_SIMULATION_INTERFACES: "REQUEST_SIMULATION_INTERFACES",
  RECEIVE_SIMULATION_INTERFACES: "RECEIVE_SIMULATION_INTERFACES",


  REQUEST_SIMULATION_CAPTURES: "REQUEST_SIMULATION_CAPTURES",
  RECEIVE_SIMULATION_CAPTURES: "RECEIVE_SIMULATION_CAPTURES",

  CLEAR_ERRORS: "CLEAR_ERRORS",


  RECEIVE_INITIAL_DATA : "RECEIVE_INITIAL_DATA",

  SHOW_MODAL: "SHOW_MODAL",
  HIDE_MODAL: "HIDE_MODAL",

  REQUEST_COHORTS: "REQUEST_COHORTS",
  RECEIVE_COHORTS: "RECEIVE_COHORTS",

  REQUEST_COURSES_GROUP: "REQUEST_COURSES_GROUP",
  RECEIVE_COURSES_GROUP: "RECEIVE_COURSES_GROUP",

  RECEIVE_SOCKET_MSG: 'RECEIVE_SOCKET_MSG',

  RESET_CONTROLBOARD: 'RESET_CONTROLBOARD',
  RESET_CONTROLBOARD_MSG: 'RESET_CONTROLBOARD_MSG',
  RESET_CONTROLBOARD_FORM: 'RESET_CONTROLBOARD_FORM',
  RESET_CONSOLE: 'RESET_CONSOLE',

  CLEAR_CONTROL_NOTIFY_MSG: 'CLEAR_CONTROL_NOTIFY_MSG',
  CLEAR_GRADER_NOTIFY_MSG: 'CLEAR_GRADER_NOTIFY_MSG',

  CONTROLBOARD_SOCKET_STORE: 'CONTROLBOARD_SOCKET_STORE',

  REQUEST_RUNNING_LABS: "REQUEST_RUNNING_LABS",
  RECEIVE_RUNNING_LABS: "RECEIVE_RUNNING_LABS",

  REQUEST_RUNNING_LAB_NODES: "REQUEST_RUNNING_LAB_NODES",
  RECEIVE_RUNNING_LAB_NODES: "RECEIVE_RUNNING_LAB_NODES",

  RESET_REPORT_CONTENTS: "RESET_REPORT_CONTENTS",

  RECEIVE_GRADER_WHITEBOARD_DATA: "RECEIVE_GRADER_WHITEBOARD_DATA",
  CLEAR_WHITEBOARD_DATA: 'CLEAR_WHITEBOARD_DATA',

  RESET_GRADER_CONTENTS: "RESET_GRADER_CONTENTS",

  REMOVE_FAILED_ENTITY: "REMOVE_FAILED_ENTITY",
  REMOVE_ALL_FAILED_ENTITY: 'REMOVE_ALL_FAILED_ENTITY',

  SET_FOLDER_NAME: 'SET_FOLDER_NAME',
  SET_LAB_NAME: 'SET_LAB_NAME',

  SEND_NOTIFICATION: 'SEND_NOTIFICATION',

  SET_ACTIVE_PODS: 'SET_ACTIVE_PODS',
  SET_POD_DEVICES: 'SET_POD_DEVICES',




};

export default Constants
